# Generated by Django 2.2.10 on 2021-07-13 08:42
from django.contrib.auth.models import User
from django.db import migrations


def create_initial_data(apps, schema_editor):
    User.objects.create_user(
        username='admin',
        password='admin',
        is_staff=True,
        is_superuser=True,
    )

    for i in range(3):
        User.objects.create_user(
            username=f'user_{i}',
            password=f'user_{i}',
        )


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
