# Generated by Django 2.2.10 on 2021-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210713_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
